import { useState, useContext } from "react";
import { motion } from "framer-motion";
import { Check, Loader2, Sparkles, Zap, Star } from "lucide-react";
import { createOrder, verifyPayment } from "../services/paymentApi";
import { useNavigate } from "react-router-dom";
import { AuthContext } from "../Context/AuthContext";
import Navbar from "../components/Navbar";

const plans = [
  {
    name: "basic",
    displayName: "Basic",
    price: 99,
    credits: 5,
    icon: <Zap className="h-6 w-6 text-blue-500" />,
    features: [
      "5 Resume Analysis Credits",
      "Basic Feedback",
      "Standard Support",
    ],
    color: "from-blue-50 to-blue-100",
    borderColor: "border-blue-200",
    buttonColor: "bg-blue-600 hover:bg-blue-700",
  },
  {
    name: "pro",
    displayName: "Pro",
    price: 299,
    credits: 25,
    icon: <Sparkles className="h-6 w-6 text-emerald-500" />,
    features: [
      "25 Resume Analysis Credits",
      "Detailed AI Feedback",
      "Priority Support",
      "Interview Prep",
    ],
    color: "from-emerald-50 to-emerald-100",
    borderColor: "border-emerald-200",
    buttonColor: "bg-emerald-600 hover:bg-emerald-700",
    popular: true,
  },
  {
    name: "super",
    displayName: "Super",
    price: 499,
    credits: 50,
    icon: <Star className="h-6 w-6 text-purple-500" />,
    features: [
      "50 Resume Analysis Credits",
      "Advanced AI Feedback",
      "24/7 Premium Support",
      "Unlimited Interview Prep",
      "Custom Templates",
    ],
    color: "from-purple-50 to-purple-100",
    borderColor: "border-purple-200",
    buttonColor: "bg-purple-600 hover:bg-purple-700",
  },
];

const loadRazorpayScript = () => {
  return new Promise((resolve) => {
    const script = document.createElement("script");
    script.src = "https://checkout.razorpay.com/v1/checkout.js";
    script.onload = () => resolve(true);
    script.onerror = () => resolve(false);
    document.body.appendChild(script);
  });
};

const Pricing = () => {
  const [loadingPlan, setLoadingPlan] = useState(null);
  const [message, setMessage] = useState({ text: "", type: "" });
  const navigate = useNavigate();
  const { user, setUser } = useContext(AuthContext);

  const handlePayment = async (plan) => {
    setLoadingPlan(plan.name);
    setMessage({ text: "", type: "" });

    try {
      const isScriptLoaded = await loadRazorpayScript();
      if (!isScriptLoaded) {
        setMessage({
          text: "Razorpay SDK failed to load. Are you online?",
          type: "error",
        });
        setLoadingPlan(null);
        return;
      }

      // Create Order from our backend
      const data = await createOrder(plan.name);

      if (!data.success) {
        setMessage({
          text: data.message || "Failed to create order",
          type: "error",
        });
        setLoadingPlan(null);
        return;
      }

      const options = {
        key: data.key, // Public Key from backend
        amount: plan.price * 100, // Amount in paise
        currency: "INR",
        name: "GenAI Resume Analyzer",
        description: `Purchase ${plan.displayName} Plan`,
        order_id: data.order.id, // Order ID generated by Razorpay
        handler: async function (response) {
          try {
            // Verify payment on the backend
            const verifyData = await verifyPayment({
              razorpay_order_id: response.razorpay_order_id,
              razorpay_payment_id: response.razorpay_payment_id,
              razorpay_signature: response.razorpay_signature,
              paymentId: data.paymentId,
            });

            if (verifyData.success) {
              setMessage({
                text: "Payment successful! Tokens added.",
                type: "success",
              });
              // Update local user tokens to reflect the purchase immediately
              if (user) {
                setUser({ ...user, tokens: (user.tokens || 0) + plan.credits });
              }
              // Redirect to home after a few seconds
              setTimeout(() => {
                navigate("/");
              }, 3000);
            } else {
              setMessage({
                text: verifyData.message || "Payment verification failed",
                type: "error",
              });
            }
          } catch (error) {
            setMessage({ text: "Payment verification failed", type: "error" });
          }
        },
        prefill: {
          name: user?.name || "",
          email: user?.email || "",
          contact: user?.phoneNo || "",
        },
        theme: {
          color: "#059669", // Tailwind emerald-600
        },
      };

      const paymentObject = new window.Razorpay(options);
      paymentObject.on("payment.failed", function (response) {
        setMessage({
          text: response.error.description || "Payment failed",
          type: "error",
        });
      });

      paymentObject.open();
    } catch (error) {
      console.error(error);
      setMessage({ text: "Something went wrong", type: "error" });
    } finally {
      setLoadingPlan(null);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <Navbar />
      <main className="py-20 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <motion.h1
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-4xl font-extrabold text-gray-900 sm:text-5xl"
          >
            Simple, transparent{" "}
            <span className="text-emerald-600">pricing</span>
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="mt-4 text-xl text-gray-600"
          >
            Choose the perfect plan to boost your career with AI-powered resume
            analysis.
          </motion.p>
        </div>

        {message.text && (
          <div
            className={`mb-8 p-4 rounded-xl text-center max-w-2xl mx-auto ${message.type === "error" ? "bg-red-50 text-red-700 border border-red-200" : "bg-emerald-50 text-emerald-700 border border-emerald-200"}`}
          >
            {message.text}
          </div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-start">
          {plans.map((plan, index) => (
            <motion.div
              key={plan.name}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 * (index + 1) }}
              className={`relative bg-white rounded-3xl p-8 shadow-sm border-2 ${plan.popular ? "border-emerald-500 shadow-xl scale-105 z-10" : "border-gray-100 hover:border-gray-200"} transition-all`}
            >
              {plan.popular && (
                <div className="absolute top-0 right-1/2 translate-x-1/2 -translate-y-1/2 bg-emerald-500 text-white px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wide">
                  Most Popular
                </div>
              )}

              <div className="flex items-center gap-4 mb-6">
                <div
                  className={`p-3 rounded-2xl bg-gradient-to-br ${plan.color} ${plan.borderColor} border`}
                >
                  {plan.icon}
                </div>
                <h3 className="text-2xl font-bold text-gray-900">
                  {plan.displayName}
                </h3>
              </div>

              <div className="mb-6">
                <span className="text-5xl font-extrabold text-gray-900">
                  ₹{plan.price}
                </span>
                <span className="text-gray-500 font-medium">/one-time</span>
              </div>

              <p className="text-gray-600 mb-8 font-medium">
                Get {plan.credits} analysis credits
              </p>

              <ul className="space-y-4 mb-8">
                {plan.features.map((feature, i) => (
                  <li key={i} className="flex items-start">
                    <Check className="h-5 w-5 text-emerald-500 shrink-0 mr-3" />
                    <span className="text-gray-600">{feature}</span>
                  </li>
                ))}
              </ul>

              <button
                onClick={() => handlePayment(plan)}
                disabled={loadingPlan === plan.name}
                className={`w-full py-4 rounded-xl font-bold text-white transition-all flex justify-center items-center ${plan.buttonColor} disabled:opacity-70 disabled:cursor-not-allowed`}
              >
                {loadingPlan === plan.name ? (
                  <Loader2 className="h-5 w-5 animate-spin" />
                ) : (
                  "Choose Plan"
                )}
              </button>
            </motion.div>
          ))}
        </div>
      </main>
    </div>
  );
};

export default Pricing;
